# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: leemingeer/sample-scheduler:v1.0.9.2
  namespace: default
  replicaCount: 1
